### ISSUE TITLE
Problem of CyberRT with Python

### ISSUE THREAD

**Issue by vladostan** [ApolloAuto/apollo#10681]
I'm trying to run examples and tests from [https://github.com/ApolloAuto/apollo/tree/master/cyber/python/cyber_py3](url). 

Only few scripts work for me, like test_init.py. But for others I've got the error. 

For example running test_recorder.py gives the following error:

Traceback (most recent call last):
  File "test_record.py", line 23, in <module>
    from cyber.proto import record_pb2
ModuleNotFoundError: No module named 'cyber'

The similar error is when running test_cyber.py

Traceback (most recent call last):
  File "test_cyber.py", line 25, in <module>
    from modules.common.util.testdata.simple_pb2 import SimpleMessage
ModuleNotFoundError: No module named 'modules'

How could i fix this?

**Comment by vladostan** [comment]
Found a solution here: https://github.com/ApolloAuto/apollo/tree/master/modules/tools
Needed to source scripts/apollo_base.sh
