### ISSUE TITLE
Dreamview frontend compile problem, libpng-dev

### ISSUE THREAD

**Issue by Kailiangdong** [ApolloAuto/apollo#11077]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**:18.04
- **Apollo installed from (source or binary)**:source,docker
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:5.0

**Hello, I make some small change to dreamview and want to rebuild the dreamview frontend, but have some error.
First I go to /modules/dreamview/frontend and run "yarn install", got the following error message.**
```bash
node[15393]: pthread_create: Invalid argument
yarn install v1.10.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > react-rangeslider@2.2.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
[5/5] Building fresh packages...
[1/12] ⠄ pngquant-bin
[8/12] ⠄ pngquant-bin
[10/12] ⠄ node-sass
[7/12] ⠄ optipng-bin
error /apollo/modules/dreamview/frontend/node_modules/imagemin-pngquant/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /apollo/modules/dreamview/frontend/node_modules/imagemin-pngquant/node_modules/pngquant-bin
Output:
node[15744]: pthread_create: Invalid argument
  ⚠ unable to verify the first certificate
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ MaxRedirectsError: pngquant failed to build, make sure that libpng-dev is installed
    at ClientRequest.fn.request.res (/apollo/modules/dreamview/frontend/node_modules/imagemin-pngquant/node_modules/got/index.js:69:23)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:440:20)
"
```

**It seems I should install libpng-dev in container, but every time I install it, it will select libpng12-dev to install. Can not install libpng-dev
I try following link ,but fail(https://askubuntu.com/questions/720361/cant-install-libpng-dev/720391#720391?newreg=746e2736511746a5a82d90ad9a633dcd)
I don't know everyone have same problem with me. If help, very thanksful.**

**Comment by Kailiangdong** [comment]
yarn remove image-websocket-loader, and install 4.5.0 version. Solved. It is a bug.

**Comment by 1power1** [comment]
> yarn remove image-websocket-loader, and install 4.5.0 version. Solved. It is a bug.

I also encountered the same problem. Can you tell me the specific code? Is it executed inside or outside of docker? thank you very much.
