### ISSUE TITLE
cyber_channel echo TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes

### ISSUE THREAD

**Issue by xuehuan-yang** [ApolloAuto/apollo#13313]
We appreciate you go through Apollo documentations and search previous issues before creating an new one. If neither of the sources helped you with your issues, please report the issue using the following form. Please note missing info can delay the response time.

### System information

- **OS Platform and Distribution ( Linux Ubuntu 18.04)**:
- **Apollo installed from (source)**:
- **Apollo version (pre6)**:

### Steps to reproduce the issue:
- **Please use bullet points and include as much details as possible**:
1 $ dev_into
2 $ cyber_monitor [perform good]
3 $ cyber_channel list [perform good]
4 $ cyber_channel echo /apollo/perception/obstacles  [shows us the following error]
### Supporting materials (screenshots, command lines, code/script snippets):

![Screenshot from 2021-01-14 09-26-42](https://user-images.githubusercontent.com/32502151/104532840-23058680-564c-11eb-9d0b-146b9da595db.png)

![Screenshot from 2021-01-14 09-38-16](https://user-images.githubusercontent.com/32502151/104532912-4d574400-564c-11eb-81e5-ff6bed153d4c.png)

@in_dev_docker:/apollo$ cyber_channel echo /apollo/perception/obstacles
E0114 09:26:37.101795  7595 py_cyber.cc:654] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 233, in reader_callback
    sub[1](proto)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 351, in callback
    print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 364, in get_debugstring_rawmsgdata
    return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
**SystemError: <built-in function PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata> returned a result with an error set
E0114 09:26:37.368297  7596 py_cyber.cc:654] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 233, in reader_callback
    sub[1](proto)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 351, in callback
    print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 364, in get_debugstring_rawmsgdata
    return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
SystemError: <built-in function PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata> returned a result with an error set
E0114 09:26:37.652420  7597 py_cyber.cc:654] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 233, in reader_callback
    sub[1](proto)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 351, in callback
    print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 364, in get_debugstring_rawmsgdata
    return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
SystemError: <built-in function PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata> returned a result with an error set
E0114 09:26:37.928679  7597 py_cyber.cc:654] [cyber_py]cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata failed!
TypeError: cyber_PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata() argument 1 must be str, not bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 233, in reader_callback
    sub[1](proto)
  File "/apollo/cyber/tools/cyber_channel/cyber_channel", line 351, in callback
    print(cyber.ChannelUtils.get_debugstring_rawmsgdata(msgtype, raw_data))
  File "/apollo/cyber/python/cyber_py3/cyber.py", line 364, in get_debugstring_rawmsgdata
    return _CYBER.PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata(msg_type, rawmsgdata)
SystemError: <built-in function PyChannelUtils_get_debugstring_by_msgtype_rawmsgdata> returned a result with an error set

Appreciate it your kind support and assistance.

**Comment by changsh726** [comment]
This issue has been fixed in the master branch. Since the pre6 branch is no longer maintained, you can refer to the pull request #12280 or use the master branch instead.
