### ISSUE TITLE
在公司内网使用proxy代理build5.5编译问题无法解决，求助

### ISSUE THREAD

**Issue by maccoo2012** [ApolloAuto/apollo#13523]
INFO] Building on x86_64...
[INFO] Building with --jobs=16 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@com_google_absl' (requested by nodes 'REPOSITORY:@com_google_absl')
INFO: (03-08 02:52:07.568) Elapsed time: 2.947s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@com_google_absl' (requested by nodes 'REPOSITORY:@com_google_absl')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:476)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.sun.security.ntlm.Client.type3(Client.java:161)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.buildType3Msg(NTLMAuthentication.java:250)
        at sun.net.www.protocol.http.ntlm.NTLMAuthentication.setHeaders(NTLMAuthentication.java:225)
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2096)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnector.connect(HttpConnector.java:112)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.establishConnection(HttpConnectorMultiplexer.java:301)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpConnectorMultiplexer.connect(HttpConnectorMultiplexer.java:126)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:200)
        at com.google.devtools.build.lib.bazel.repository.downloader.HttpDownloader.download(HttpDownloader.java:123)
        at com.google.devtools.build.lib.bazel.repository.HttpArchiveFunction.fetch(HttpArchiveFunction.java:71)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:401)

**Comment by storypku** [comment]
Hi @maccoo2012 , You should switch to another proxy in Apollo 5.5. Or else, you have to modify WORKSPACE files yourself to fix this issue in Apollo 5.5 which is not actively maintained.
Bazel's [distribution directory support](https://docs.bazel.build/versions/master/guide.html#distribution-files-directories) was added only in Apollo 6.0 (r6.0.0)  and onwards.

**Comment by maccoo2012** [comment]
> Hi @maccoo2012 , You should switch to another proxy in Apollo 5.5. Or else, you have to modify WORKSPACE files yourself to fix this issue in Apollo 5.5 which is not actively maintained.
> Bazel's [distribution directory support](https://docs.bazel.build/versions/master/guide.html#distribution-files-directories) was added since Apollo 6.0 (r6.0.0) and onwards.

how to modify WORKSPACE files in Apollo5.5?  Thank you for your reply.

**Comment by storypku** [comment]
> > Hi @maccoo2012 , You should switch to another proxy in Apollo 5.5. Or else, you have to modify WORKSPACE files yourself to fix this issue in Apollo 5.5 which is not actively maintained.
> > Bazel's [distribution directory support](https://docs.bazel.build/versions/master/guide.html#distribution-files-directories) was added since Apollo 6.0 (r6.0.0) and onwards.
> 
> how to modify WORKSPACE files in Apollo5.5? Thank you for your reply.

I am afraid that you have figure out that yourself. There is a WORKSPACE.in file in the r5.5.0 branch. 

https://github.com/ApolloAuto/apollo/blob/r5.5.0/WORKSPACE.in

Editing it requires some Bazel knowledge.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
