### ISSUE TITLE
HMI ros_node_service core dump

### ISSUE THREAD

**Issue by xiaoxq** [ApolloAuto/apollo#139]
This could be obsolete, as the core dumps were collected on around 06/25/2017.
I'm working on it but have no idea yet. Will mark as obsolete if we cannot reproduce for a period of time.

```
#0  0x00007fa643ea1404 in ?? ()
#1  0x00007fa62d7f9b00 in ?? ()
#2  0x00000000004101cf in __gnu_cxx::__exchange_and_add (__mem=0x28, __val=0)
    at /usr/include/c++/4.8/ext/atomicity.h:49
#3  0x000000000041121e in __static_initialization_and_destruction_0 (
    __initialize_p=0, __priority=40)
    at /usr/include/boost/system/error_code.hpp:222
#4  0x0000000000597447 in apollo::common::Point2D::~Point2D (
    this=0x7fa62d7f9b90, __in_chrg=<optimized out>)
    at bazel-out/local-dbg/genfiles/modules/common/proto/geometry.pb.cc:1070
#5  0x0000000000597037 in apollo::common::PointLLH::InternalSwap (this=
    0x86ee70 <google::protobuf::internal::ExtensionSet::RemoveLast(int)+666>, 
    other=0x7fa62d7f9b30)
    at bazel-out/local-dbg/genfiles/modules/common/proto/geometry.pb.cc:945
#6  0x0000000000594124 in apollo::common::protobuf_AssignDesc_modules_2fcommon_2fproto_2fgeometry_2eproto ()
    at bazel-out/local-dbg/genfiles/modules/common/proto/geometry.pb.cc:50
#7  0x00000000004106d1 in apollo::hmi::(anonymous namespace)::RunGRPCServer ()
    at modules/hmi/ros_node/ros_node_service.cc:62
```

**Comment by xiaoxq** [comment]
Cannot reproduce.
