### ISSUE TITLE
The password of root user in container 'apollo_dev_<username>'

### ISSUE THREAD

**Issue by DreamWaterFound** [ApolloAuto/apollo#14253]
### Descriptions

I met the same problem as #9219 mentioned. For some reason, I need to install the network proxy tools inside the container, which required the password of root user in container. 

Does anyone know this password? 

### Steps to reproduce the issue:
- In host:
  - `cd <APOLLO_ROOT_DIR>`
  - `sudo service docker start`
  - `bash docker/scripts/dev_start.sh` 
  - `bash docker/scripts/dev_into.sh`
- In container `apollo_dev_<username>`:
  - `sudo apt update`, with outputs:
    ```
    sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
    ```
  - `apt update`, with outputs:
    ```
    Reading package lists... Done
    E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
    E: Unable to lock directory /var/lib/apt/lists/
    ```
  - `su root`, need password.

### System information

- **OS Platform and Distribution**: Ubuntu 20.04.3 LTs with kernel 5.4.0-91-generic
- **Apollo installed from (source or binary)**: binary
- **Apollo version (3.5, 5.0, 5.5, 6.0)**: 5.5
- **Output of `apollo.sh config` if on `master` branch**: crashed, with following info:
```
guoqing@in_dev_docker:/apollo$ bash apollo.sh config
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Traceback (most recent call last):
  File "modules/tools/configurator/configurator.py", line 162, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "modules/tools/configurator/configurator.py", line 151, in main
    conf = Configurator(stdscr)
  File "modules/tools/configurator/configurator.py", line 63, in __init__
    moduleconf.parse_from_file()
  File "/apollo/modules/tools/configurator/ModuleConf.py", line 45, in parse_from_file
    mod = importlib.import_module(self.proto_file)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named modules.canbus.proto.canbus_conf_pb2
```

### Supporting materials (screenshots, command lines, code/script snippets):
The screenshot:
![Screenshot from 2022-01-05 17-11-15](https://user-images.githubusercontent.com/33981288/148191626-6fd8b243-ea5c-4fb5-ac2f-a4534f34cc92.png)

**Comment by DreamWaterFound** [comment]
Thanks for your reply! I tried the password but it didn't work.
However, I found a way to login container as root and no password required.

Just change `docker/scripts/dev_into.sh`:

```bash
docker exec \
    -u $USER \
    -e HISTFILE=/apollo/.dev_bash_hist \
    -it apollo_dev_$USER \
    /bin/bash
xhost -local:root 1>/dev/null 2>&1
```

to:

```bash
docker exec \
    -u root \
    -e HISTFILE=/apollo/.dev_bash_hist \
    -it apollo_dev_$USER \
    /bin/bash
xhost -local:root 1>/dev/null 2>&1
````

The basic usage of Docker :joy:  I forgot it
