### ISSUE TITLE
Installation failed: No such file or directory: 'cyber/tools/cyber_launch/cyber_launch.py'

### ISSUE THREAD

**Issue by felixf4xu** [ApolloAuto/apollo#14463]
**Describe the bug**

**To Reproduce**
1. Inside the docker, run `./apollo.sh build_cpu cyber`
2. go to folder of `apollo/bazel-bin`, then run `cyber/install /apollo`, I didn't find the document, but I guess it will install apollo cyber
3. See error message like this

```
-- Up-to-date: /apollo/cyber/python/internal/_cyber_parameter_wrapper.so
-- Installing: /apollo/bin/cyber_launch
Traceback (most recent call last):
  File "cyber/install", line 490, in <module>
    main(sys.argv[1:])
  File "cyber/install", line 463, in main
    install("cyber/tools/cyber_launch/cyber_launch.py", "bin/cyber_launch")
  File "cyber/install", line 156, in install
    copy_or_link(src, dst_full)
  File "cyber/install", line 131, in copy_or_link
    shutil.copy2(src, dst)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'cyber/tools/cyber_launch/cyber_launch.py'
```

**Expected behavior**
apollo cyber files install to `/apollo` folder

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Jetson, Ubuntu 18, aarch64
 - Version v7.0.0

**Additional context**
I have checked in the folder of `cyber/tools/cyber_launch/`, there is no `cyber_launch.py` but `cyber_launch` without `.py`.
so in the file of `apollo/cyber/tools/cyber_launch/BUILD`
```bazel
# Note(storypku):
# Workaround for install support of Python not ready.
install_files(
    name = "install",
    dest = "bin",
    files = [
        ":cyber_launch.py",
    ],
    rename = {
        "bin/cyber_launch.py": "cyber_launch",
    },
)
```
`"bin/cyber_launch.py": "cyber_launch",` should be `"bin/cyber_launch": "cyber_launch",` ? (without `.py`)

**Comment by daohu527** [comment]
Do you want to install the cyber or just run it?

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
