### ISSUE TITLE
[Question]-Apollo Auto can send and Receive data(like lidar and Radar) using WebSocket to Application via listen port- TCP/UPD?

### ISSUE THREAD

**Issue by anilbommareddy** [ApolloAuto/apollo#14737]
The Apollo Auto simulator Can sends like car telemetry information the data specifications to the application using WebSocketi.e WebSocket(uWebSockets) Data-describes the JSON object send back from the simulator command server.

For sample example i.e understanding:
https://github.com/shazraz/Extended-Kalman-Filter.

Here bins tested with Udacity SDC Term 2 Simulator (Extended-Kalman-Filter connected/communicat Udacity on Port TCP and data receive Json msg)
Similar Apollo Auto Can be used send/receive other from other Application
I think Apollo-Auto dream view connected via WebSocket. so, Apollo auto will be provided WebSocket interfaces to send/receive data to Register Application ?

**Comment by daohu527** [comment]
Yes, dreamview already use websocket to send data, you can also ref the `modules/bridge` module to send data to other software

**Comment by anilbommareddy** [comment]
@daohu527 could you please let know how to test module/bridge.?


root@in_dev_docker:/apollo/bazel-bin/modules/bridge# ./udp_bridge_sender_cpplint
Traceback (most recent call last):
  File "./udp_bridge_sender_cpplint", line 178, in <module>
    Main()
  File "./udp_bridge_sender_cpplint", line 145, in Main
    'Cannot exec() %r: file not found.' % main_filename
AssertionError: Cannot exec() '/root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/bridge/udp_bridge_sender_cpplint.runfiles/apollo/../google_styleguide/cpplint/cpplint.py': file not found.
root@in_dev_docker:/apollo/bazel-bin/modules/bridge/test# ./bridge_sender_test
./bridge_sender_test: error while loading shared libraries: libgflags.so.2.2: cannot open shared object file: No such file or directory
root@in_dev_docker:/apollo/bazel-bin/modules/bridge/test#
