### ISSUE TITLE
CMD:cyber_node, cyber_channel is not working???

### ISSUE THREAD

**Issue by zhuheixin** [ApolloAuto/apollo#15119]
I can't use some of the functions of cyber,such as cyber_node, cyber_channel.
Apollo version: 8.0

### Steps to reproduce the issue:

miao@in-dev-docker:/apollo_workspace$ cyber_node list 
Traceback (most recent call last):
  File "/opt/apollo/neo/packages/cyber-dev/latest/bin/cyber_node.runfiles/apollo/cyber/tools/cyber_node/cyber_node.py", line 23, in <module>
    from cyber.python.cyber_py3 import cyber
ModuleNotFoundError: No module named 'cyber.python'
miao@in-dev-docker:/apollo_workspace$ cyber_channel list 
Traceback (most recent call last):
  File "/opt/apollo/neo/packages/cyber-dev/latest/bin/cyber_channel.runfiles/apollo/cyber/tools/cyber_channel/cyber_channel.py", line 23, in <module>
    from cyber.python.cyber_py3 import cyber_time
ModuleNotFoundError: No module named 'cyber.python'

**Comment by WTSRUVF** [comment]
Firstly, please ensure that you have compiled the code globally, using "buildtool build" in the package management environment and "bash apollo. sh build" in the source code environment. Secondly, please ensure that the user you downloaded the code from is the same as the user inside the container, both being 'miao'. And please avoid taking turns intervening in the code between root and 'miao' users.
