### ISSUE TITLE
Apollo 10.0环境下编译application-core失败

### ISSUE THREAD

**Issue by paolo-dai** [ApolloAuto/apollo#15598]
将Apollo 9.0升级到Apollo 10.0后，在amd64和arm64上均出现错误。
在amd64上编译application-core时，遇到“No such file or directory: '/root/.apollo/available_check”错误。
```
ps@ps:~/apollo_ws/application-core$ sudo aem start
[WARN ] 2024-12-04 12:08:40 apollo environment `10.0.0_pkg' already exists, enter directly. Or you can use flag `--force' to recreate it.
root@in-dev-docker:/apollo_workspace# 
root@in-dev-docker:/apollo_workspace# buildtool build -p core
/usr/bin/buildtool:36: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
[buildtool] 2024-12-04 12:09:14 INFO Download the latest package index to construct a local database...
[buildtool] 2024-12-04 12:09:18 INFO update repo apollo-tools
[buildtool] 2024-12-04 12:09:18 INFO update repo apollo-core-jammy
[buildtool] 2024-12-04 12:09:18 INFO update repo apollo-core
Traceback (most recent call last):
  File "/usr/bin/buildtool", line 110, in check_version_available
    update_pkg_version_available(VERSION_AVAILABLE_CHECK_PATH, code)
  File "/opt/apollo/neo/packages/buildtool/10.0.0-rc1-r1/core/__init__.py", line 114, in update_pkg_version_available
    with open(file_path, 'w') as fn:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.apollo/available_check'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/buildtool", line 300, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/buildtool", line 287, in main
    obj = PackageBuilder()
  File "/usr/bin/buildtool", line 97, in __init__
    self.check_version_available(repository)
  File "/usr/bin/buildtool", line 132, in check_version_available
    update_pkg_version_available(VERSION_AVAILABLE_CHECK_PATH, 500)
  File "/opt/apollo/neo/packages/buildtool/10.0.0-rc1-r1/core/__init__.py", line 114, in update_pkg_version_available
    with open(file_path, 'w') as fn:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.apollo/available_check'
```

在arm64（Orin Nx）上编译application-core时，遇到“package architecture (amd64) does not match system (arm64)“的错误
```
[onx@in-dev-docker:/apollo_workspace]$ buildtool build -p core
[buildtool] 2024-12-04 04:03:51 INFO Download the latest package index to construct a local database...
[buildtool] 2024-12-04 04:03:52 INFO update repo apollo-tools
[buildtool] 2024-12-04 04:03:53 INFO update repo apollo-core-jammy
[buildtool] 2024-12-04 04:03:53 INFO update repo apollo-core
[buildtool] 2024-12-04 04:03:54 INFO Reconfigure apollo enviroment setup
[buildtool] 2024-12-04 04:04:06 INFO Analyzing dependencies topological graph...
Found possible Python library paths:
  /usr/lib/python3.8/dist-packages
  /usr/local/lib/python3.8/dist-packages
  /usr/lib/python3/dist-packages
Found CUDA 11.4 in:
    /usr/local/cuda-11.4/targets/aarch64-linux/lib
    /usr/local/cuda-11.4/targets/aarch64-linux/include
Found cuDNN 8 in:
    /usr/lib/aarch64-linux-gnu
    /usr/include
Found TensorRT 8 in:
    /usr/lib/aarch64-linux-gnu
    /usr/include/aarch64-linux-gnu


[buildtool] 2024-12-04 04:04:07 INFO Processing libfreetype6
[buildtool] 2024-12-04 04:04:07 INFO Processing libtiff5
[buildtool] 2024-12-04 04:04:07 INFO Processing vanjee-driver
[buildtool] 2024-12-04 04:04:09 INFO Install vanjee-driver...
[buildtool] 2024-12-04 04:04:15 INFO vanjee-driver successfully installed
[buildtool] 2024-12-04 04:04:15 INFO Processing 3rd-absl
[buildtool] 2024-12-04 04:04:15 INFO Install 3rd-absl...
[buildtool] 2024-12-04 04:04:17 INFO install 3rd-absl...                                                                
[buildtool] 2024-12-04 04:04:22 ERROR Encounter ErrCode.AptErr
[buildtool] 2024-12-04 04:04:22 ERROR hint: Encouter error during install apollo apt package 3rd-absl, detail:
stdout: 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  gfortran gfortran-8 gfortran-9 ibverbs-providers libboost-dev
  libboost1.71-dev libcaf-openmpi-3 libcoarrays-dev libcoarrays-openmpi-dev
  libevent-2.1-7 libevent-core-2.1-7 libevent-dev libevent-extra-2.1-7
  libevent-openssl-2.1-7 libevent-pthreads-2.1-7 libflann-dev libflann1.9
  libgfortran-8-dev libgfortran-9-dev libhdf5-mpi-dev libhdf5-openmpi-103
  libhdf5-openmpi-dev libhwloc-dev libhwloc-plugins libhwloc15 libibverbs-dev
  libibverbs1 liblz4-dev libncurses-dev libncurses5-dev libnl-3-dev
  libnl-route-3-dev libnuma-dev libopenmpi-dev libopenmpi3 libpmix2
  libtinyxml2-6a libtinyxml2-dev libxnvctrl0 mpi-default-dev openmpi-bin
  openmpi-common
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  apollo-neo-3rd-absl
The following NEW packages will be installed:
  apollo-neo-3rd-absl:amd64
0 upgraded, 1 newly installed, 1 to remove and 227 not upgraded.
Need to get 0 B/1701 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /opt/apollo/neo/playgroud/3rd-absl_10.0.0-beta-r1.deb apollo-neo-3rd-absl amd64 10.0.0-beta-r1 [1701 kB]
dpkg: error processing archive /opt/apollo/neo/playgroud/3rd-absl_10.0.0-beta-r1.deb (--unpack):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 /opt/apollo/neo/playgroud/3rd-absl_10.0.0-beta-r1.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
[buildtool] 2024-12-04 04:04:22 ERROR Encounter ErrCode.AptErr
[buildtool] 2024-12-04 04:04:22 ERROR hint: Aborting process
stderr: [onx@in-dev-docker:/apollo_workspace]$ 
```

**Comment by hearto1314** [comment]
1. 不要使用sudo aem start，直接aem start，如果提示再输入密码

**Comment by lukeliuli** [comment]
WSL 安装 apollo10 出现错误 No such file or directory: '/root/.apollo/available_check'

![Image](https://github.com/user-attachments/assets/c0a41fa1-e41d-4daf-9970-9181a9764a62)

**Comment by cctvyyds** [comment]
> WSL 安装 apollo10 出现错误 No such file or directory: '/root/.apollo/available_check'
> 
> ![Image](https://github.com/user-attachments/assets/c0a41fa1-e41d-4daf-9970-9181a9764a62)

请问你解决了吗？我也是这个问题
