### ISSUE TITLE
bash scripts/hmi.sh bash scripts/hmi.sh

### ISSUE THREAD

**Issue by shophome** [ApolloAuto/apollo#246]
michah@in_dev_docker:/apollo$ bash scripts/hmi.sh
Start roscore...
HMI ros node service running at localhost:8887
Failed to start HMI.
Traceback (most recent call last):
  File "modules/hmi/web/hmi_main.py", line 23, in <module>
    import handlers
  File "/apollo/modules/hmi/web/handlers.py", line 27, in <module>
    import config
  File "/apollo/modules/hmi/web/config.py", line 26, in <module>
    import modules.hmi.proto.config_pb2 as config_pb2
ImportError: No module named modules.hmi.proto.config_pb2
michah@in_dev_docker:/apollo$ ^C

**Comment by tcarmichael** [comment]
Make sure you run
`bash apollo.sh build`
