### ISSUE TITLE
roscore cannot start in apollo docker 

### ISSUE THREAD

**Issue by hongkedavid** [ApolloAuto/apollo#2500]
I pulled the latest apollo repo and docker image (apolloauto/apollo with TAG "dev-x86_64-20180103_1300" and image ID "1fa0684d4b3b") and followed the instructions in [README](https://github.com/ApolloAuto/apollo/blob/master/README.md) to try to start the demo. The build has passed. But the roscore has not been started (dreamview process is started but I cannot get access to it through a web browser) every time I run "bash scripts/bootstrap.sh". 

The output of _data/log/roscore.out_ is as follows. The error persists even after I clean my build and rebuild apollo.
```
ERROR: could not contact master [http://in_dev_docker:11311/]
The traceback for the exception was written to the log file
... logging to /home/david/.ros/log/b539f348-fbcc-11e7-b604-ecf4bbc428c8/roslaunch-in_dev_docker-14447.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://in_dev_docker:50849/
ros_comm version 1.11.21


SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES

auto-starting new master
process[master]: started with pid [14490]
Traceback (most recent call last):
  File "/home/tmp/ros/bin/rosmaster", line 34, in <module>
    import rosmaster
  File "/home/tmp/ros/lib/python2.7/dist-packages/rosmaster/__init__.py", line 35, in <module>
    from .main import rosmaster_main
  File "/home/tmp/ros/lib/python2.7/dist-packages/rosmaster/main.py", line 43, in <module>
    import rosmaster.master
  File "/home/tmp/ros/lib/python2.7/dist-packages/rosmaster/master.py", line 45, in <module>
    import rosgraph.xmlrpc
  File "/home/tmp/ros/lib/python2.7/dist-packages/rosgraph/__init__.py", line 36, in <module>
    from . masterapi import Master, MasterFailure, MasterError, MasterException
  File "/home/tmp/ros/lib/python2.7/dist-packages/rosgraph/masterapi.py", line 49, in <module>
    from rospy.impl.broadcast_manager import BroadcastManager
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/client.py", line 68, in <module>
    from roscpp.srv import GetLoggers, GetLoggersResponse, SetLoggerLevel, SetLoggerLevelResponse
  File "/home/tmp/ros/lib/python2.7/dist-packages/roscpp/srv/__init__.py", line 1, in <module>
    from ._Empty import *
  File "/home/tmp/ros/lib/python2.7/dist-packages/roscpp/srv/_Empty.py", line 2, in <module>
    """autogenerated by genpy from roscpp/EmptyRequest.msg. Do not edit."""
KeyboardInterrupt
[master] killing on exit
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr

```

The detailed ros log is as follows.
```
[roslaunch][INFO] 2018-01-17 16:23:50,063: Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2018-01-17 16:23:50,204: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2018-01-17 16:23:50,211: roslaunch starting with args ['roscore', '--core']
[roslaunch][INFO] 2018-01-17 16:23:50,216: roslaunch env is {'ROSCONSOLE_FORMAT': '${file}:${line} ${function}() [${severity}] [${time}]: ${message}', 'HOSTNAME': 'in_dev_docker', 'ROS_DISTRO': 'indigo', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'ROSLISP_PACKAGE_DIRECTORIES': '', 'CPATH': '/home/tmp/ros/include', 'USER': 'david', 'HOME': '/home/david', 'PATH': '/usr/local/cuda-8.0/bin:/home/tmp/ros/bin:/apollo/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'CMAKE_PREFIX_PATH': '/home/tmp/ros', 'LD_LIBRARY_PATH': '/usr/local/cuda-8.0/lib64:/home/tmp/ros/lib:/apollo/lib:/apollo/bazel-genfiles/external/caffe/lib:/home/caros/secure_upgrade/depend_lib', 'ROS_DOMAIN_ID': '68112177', 'TERM': 'xterm', 'ROS_LOG_FILENAME': '/home/david/.ros/log/b539f348-fbcc-11e7-b604-ecf4bbc428c8/roslaunch-in_dev_docker-14447.log', 'SHLVL': '2', 'DISPLAY': ':0', 'DOCKER_IMG': 'apolloauto/apollo:dev-x86_64-20180103_1300', 'APOLLO_IN_DOCKER': 'true', 'DEBIAN_FRONTEND': 'noninteractive', 'ROS_ETC_DIR': '/home/tmp/ros/etc/ros', 'DOCKER_USER': 'david', 'DOCKER_GRP_ID': '1007', 'PYTHONPATH': '/usr/local/lib/python2.7/dist-packages:/apollo/py_proto:/apollo/modules/tools:/home/tmp/ros/lib/python2.7/dist-packages', 'ROS_ROOT': '/home/tmp/ros/share/ros', 'DOCKER_USER_ID': '1007', 'PKG_CONFIG_PATH': '/home/tmp/ros/lib/pkgconfig', 'ROS_PACKAGE_PATH': '/home/tmp/ros/share:/home/tmp/ros/stacks', 'DOCKER_GRP': 'david', 'APOLLO_BASE_SOURCED': '1', '_': '/usr/bin/nohup', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'CAFFE_ROOT': '/apollo/bazel-genfiles/external/caffe', 'OLDPWD': '/apollo', 'APOLLO_BIN_PREFIX': '/apollo', 'CPLUS_INCLUDE_PATH': '/usr/local/cuda-8.0/include:', 'PWD': '/apollo', 'ROS_MASTER_URI': 'http://localhost:11311', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'C_INCLUDE_PATH': '/usr/local/cuda-8.0/include:'}
[roslaunch][INFO] 2018-01-17 16:23:50,220: starting in server mode
[roslaunch.parent][INFO] 2018-01-17 16:23:50,229: starting roslaunch parent run
[roslaunch][INFO] 2018-01-17 16:23:50,239: loading roscore config file /home/tmp/ros/etc/ros/roscore.xml
[roslaunch][INFO] 2018-01-17 16:23:54,545: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.pmon][INFO] 2018-01-17 16:23:54,565: start_process_monitor: creating ProcessMonitor
[roslaunch.pmon][INFO] 2018-01-17 16:23:54,571: created process monitor <ProcessMonitor(ProcessMonitor-1, initial daemon)>
[roslaunch.pmon][INFO] 2018-01-17 16:23:54,582: start_process_monitor: ProcessMonitor started
[roslaunch.parent][INFO] 2018-01-17 16:23:54,607: starting parent XML-RPC server
[roslaunch.server][INFO] 2018-01-17 16:23:54,614: starting roslaunch XML-RPC server
[roslaunch.server][INFO] 2018-01-17 16:23:54,619: waiting for roslaunch XML-RPC server to initialize
[xmlrpc][INFO] 2018-01-17 16:23:54,627: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-01-17 16:23:54,641: Started XML-RPC server [http://in_dev_docker:50849/]
[xmlrpc][INFO] 2018-01-17 16:23:54,645: xml rpc node: starting XML-RPC server
[roslaunch][INFO] 2018-01-17 16:23:54,705: started roslaunch server http://in_dev_docker:50849/
[roslaunch.parent][INFO] 2018-01-17 16:23:54,710: ... parent XML-RPC server started
[roslaunch][INFO] 2018-01-17 16:23:54,718: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:54,860: auto-starting new master
[roslaunch][INFO] 2018-01-17 16:23:54,867: create_master_process: rosmaster, /home/tmp/ros/share/ros, 11311, 3, None
[roslaunch][INFO] 2018-01-17 16:23:54,870: process[master]: launching with args [['rosmaster', '--core', '-p', '11311', '-w', '3']]
[roslaunch.pmon][INFO] 2018-01-17 16:23:54,875: ProcessMonitor.register[master]
[roslaunch.pmon][INFO] 2018-01-17 16:23:54,879: ProcessMonitor.register[master] complete
[roslaunch][INFO] 2018-01-17 16:23:54,882: process[master]: starting os process
[roslaunch][INFO] 2018-01-17 16:23:54,887: process[master]: start w/ args [['rosmaster', '--core', '-p', '11311', '-w', '3', '__log:=/home/david/.ros/log/b539f348-fbcc-11e7-b604-ecf4bbc428c8/master.log']]
[roslaunch][INFO] 2018-01-17 16:23:54,891: process[master]: cwd will be [/home/david/.ros]
[roslaunch][INFO] 2018-01-17 16:23:56,137: process[master]: started with pid [14490]
[roslaunch][INFO] 2018-01-17 16:23:56,166: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:56,298: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:56,411: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:56,523: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:56,636: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:56,748: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:56,861: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:56,973: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,085: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,197: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,377: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,494: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,606: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,719: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,837: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:57,950: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,062: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,175: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,287: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,425: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,539: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,654: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,767: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,879: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:58,991: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,103: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,216: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,328: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,452: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,578: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,690: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,802: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:23:59,914: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,026: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,139: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,251: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,363: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,477: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,603: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,717: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,829: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:00,941: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,053: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,165: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,278: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,393: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,508: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,620: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,732: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,844: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:01,956: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,077: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,196: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,310: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,422: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,534: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,647: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,759: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,871: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:02,983: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,095: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,207: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,321: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,434: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,546: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,658: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,770: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,883: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:03,995: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,107: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,220: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,334: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,447: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,559: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,742: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,856: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:04,968: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,082: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,194: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,306: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,418: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,530: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,643: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,755: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,867: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:05,979: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:06,091: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:06,203: master.is_running[http://in_dev_docker:11311/]
[roslaunch][INFO] 2018-01-17 16:24:06,214: master.is_running[http://in_dev_docker:11311/]
[roslaunch][ERROR] 2018-01-17 16:24:06,226: ERROR: could not contact master [http://in_dev_docker:11311/]
[roslaunch][ERROR] 2018-01-17 16:24:06,233: The traceback for the exception was written to the log file
[roslaunch][ERROR] 2018-01-17 16:24:06,254: Traceback (most recent call last):
  File "/home/tmp/ros/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/home/tmp/ros/lib/python2.7/dist-packages/roslaunch/parent.py", line 279, in start
    self.runner.launch()
  File "/home/tmp/ros/lib/python2.7/dist-packages/roslaunch/launch.py", line 654, in launch
    self._setup()
  File "/home/tmp/ros/lib/python2.7/dist-packages/roslaunch/launch.py", line 630, in _setup
    self._launch_master()
  File "/home/tmp/ros/lib/python2.7/dist-packages/roslaunch/launch.py", line 407, in _launch_master
    raise RLException("ERROR: could not contact master [%s]"%m.uri)
RLException: ERROR: could not contact master [http://in_dev_docker:11311/]

[roslaunch.pmon][INFO] 2018-01-17 16:24:06,265: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, started daemon 140658341824256)>
[roslaunch.pmon][INFO] 2018-01-17 16:24:06,361: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 140658341824256)>
[roslaunch.pmon][INFO] 2018-01-17 16:24:06,368: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 140658341824256)>: remaining procs are [<roslaunch.nodeprocess.LocalProcess object at 0x7feda2811e10>]
[roslaunch.pmon][INFO] 2018-01-17 16:24:06,428: ProcessMonitor exit: killing master
[roslaunch][INFO] 2018-01-17 16:24:06,432: [master] killing on exit
[roslaunch][INFO] 2018-01-17 16:24:06,436: process[master]: killing os process with pid[14490] pgid[14490]
[roslaunch][INFO] 2018-01-17 16:24:06,439: [master] sending SIGINT to pgid [14490]
[roslaunch][INFO] 2018-01-17 16:24:06,443: [master] sent SIGINT to pgid [14490]
[roslaunch][INFO] 2018-01-17 16:24:06,951: process[master]: SIGINT killed with return value 1
[roslaunch.pmon][INFO] 2018-01-17 16:24:06,956: ProcessMonitor exit: cleaning up data structures and signals
[roslaunch.pmon][INFO] 2018-01-17 16:24:06,960: ProcessMonitor exit: pmon has shutdown
[rospy.core][INFO] 2018-01-17 16:24:06,997: signal_shutdown [atexit]

```

 I guess there may be something wrong with my environment setup? I appreciate for any hint to fixing this error.

**Comment by hongkedavid** [comment]
The error seems to be caused by the timeout of master start (10sec set by default). A longer timeout value is required on my setup (i.e., 60sec). To tune that value, I changed the value in /home/tmp/ros/lib/python2.7/dist-packages/roslaunch/launch.py

`_TIMEOUT_MASTER_START = 10.0 #seconds`
to
`_TIMEOUT_MASTER_START = 60.0 #seconds`

After the change, the roscore, rosmaster and rosout process can start normally. I can also replay the demo bag and see the vehicle on Dreamview.

**Comment by Capri2014** [comment]
@hongkedavid could you submit a PR for `https://github.com/ApolloAuto/apollo/blob/master/docs/FAQs/Software_FAQs.md` ? We did not have this problem before and this might help other developers in the community.

**Comment by hongkedavid** [comment]
@Capri2014 Sure, the [pull request](https://github.com/ApolloAuto/apollo/pull/2542) has been submitted.
