### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wm901115nwpu** [ApolloAuto/apollo#2545]
When I run ./apollo.sh build , I get:
ERROR: /home/wangmeng/.cache/bazel/_bazel_wangmeng/8f255fe58fcdd5c3da4a07d7b1f89f4e/external/com_google_protobuf/BUILD:441:1: Traceback (most recent call last):
	File "/home/wangmeng/.cache/bazel/_bazel_wangmeng/8f255fe58fcdd5c3da4a07d7b1f89f4e/external/com_google_protobuf/BUILD", line 441
		cc_proto_library(name = "cc_test_protos", srcs = (L...), <4 more arguments>)
	File "/home/wangmeng/.cache/bazel/_bazel_wangmeng/8f255fe58fcdd5c3da4a07d7b1f89f4e/external/com_google_protobuf/protobuf.bzl", line 247, in cc_proto_library
		cc_libs += [default_runtime]
trying to mutate a frozen object
ERROR: /home/wangmeng/.cache/bazel/_bazel_wangmeng/8f255fe58fcdd5c3da4a07d7b1f89f4e/external/com_google_protobuf/BUILD:742:1: Traceback (most recent call last):
	File "/home/wangmeng/.cache/bazel/_bazel_wangmeng/8f255fe58fcdd5c3da4a07d7b1f89f4e/external/com_google_protobuf/BUILD", line 742
		py_proto_library(name = "python_specific_test_pro...", <6 more arguments>)
	File "/home/wangmeng/.cache/bazel/_bazel_wangmeng/8f255fe58fcdd5c3da4a07d7b1f89f4e/external/com_google_protobuf/protobuf.bzl", line 373, in py_proto_library
		py_libs += [default_runtime]
trying to mutate a frozen object
ERROR: Evaluation of query "//..." failed due to BUILD file errors

**Comment by zhxt** [comment]
Did you run this command inside docker?

**Comment by wm901115nwpu** [comment]
no, I run it terminal.

**Comment by Capri2014** [comment]
@wm901115nwpu It needs to be built inside dev dockers, see https://github.com/ApolloAuto/apollo/blob/master/README.md for me details.

**Comment by natashadsouza** [comment]
Closing this issue as it seems to be resolved.
