### ISSUE TITLE
run offline demo failed

### ISSUE THREAD

**Issue by qwetqwe** [ApolloAuto/apollo#267]
when i ran offline demo,after entering 
bash docker/scripts/release_start.sh
bash docker/scripts/release_into.sh
rosbag play docs/demo_guide/demo.bag --loop
the wrong appeard like this:
Traceback (most recent call last):
  File "/opt/ros/jade/bin/rosbag", line 35, in <module>
    rosbag.rosbagmain()
  File "/opt/ros/jade/lib/python2.7/dist-packages/rosbag/rosbag_main.py", line 883, in rosbagmain
    cmds[cmd](argv[2:])
  File "/opt/ros/jade/lib/python2.7/dist-packages/rosbag/rosbag_main.py", line 230, in play_cmd
    playpath = roslib.packages.find_node('rosbag', 'play')
  File "/opt/ros/jade/lib/python2.7/dist-packages/roslib/packages.py", line 400, in find_node
    return find_resource(pkg, node_type, filter_fn=_executable_filter, rospack=rospack)
  File "/opt/ros/jade/lib/python2.7/dist-packages/roslib/packages.py", line 495, in find_resource
    pkg_path = rospack.get_path(pkg)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 201, in get_path
    self._update_location_cache()
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 184, in _update_location_cache
    list_by_path(self._manifest_name, path, cache)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 67, in list_by_path
    root = ElementTree(None, os.path.join(d, PACKAGE_FILE))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 611, in __init__
    self.parse(file)
  File "<string>", line 38, in parse
cElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by siyangy** [comment]
This looks like you have another ROS installed in your host machine. You can probably try source scripts/apollo_base.sh to override it. I can be verified by running 'which rosbag'.

**Comment by quning78** [comment]
Closed due to no response for a while, please reopen it if you still have questions. Thanks!
