### ISSUE TITLE
issue on "Cannot replay recorded garage.csv file"

### ISSUE THREAD

**Issue by lianglia-apollo** [ApolloAuto/apollo#3588]
If you want to replay a recorded garage.csv file, please use ./scripts/rtk_replayer.sh.
If you used ./scripts/replay.sh, you might have the following error messages.

XXX@in_dev_docker:/apollo$ bash scripts/replay.sh ./data/log/garage.csv 
/use_sim_time is not set, will not subscribe to simulated time [/clock] topic
Topic not specified, start to guess
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Error: Cannot parse ./data/log/garage.csv as binary or text proto
Failed to parse file ./data/log/garage.csv
Traceback (most recent call last):
  File "/apollo/modules/tools/replay/replay_file.py", line 110, in <module>
    topic_publisher(args.topic, to_replay, period)
  File "/apollo/modules/tools/replay/replay_file.py", line 43, in topic_publisher
    topic = meta_msg.topic()
AttributeError: 'NoneType' object has no attribute 'topic'

**Comment by lianglia-apollo** [comment]
Closed as this is just for notification.
