### ISSUE TITLE
ValueError: No closing quotation in the gen vehicle protocol tool

### ISSUE THREAD

**Issue by Carlzhangk** [ApolloAuto/apollo#5141]
Hello, When I used the gen vehicle protocol tool (modules/tools/gen_vehicle_protocol) to generate the necessary files to use Apollo with my vehicle, it turned out the following error. If the issue lies in my dbc file, the file was created by Vector tool and has been used in similar CAN tools. Any direction?

Traceback (most recent call last):
  File "gen.py", line 68, in <module>
    gen(conf)
  File "gen.py", line 46, in gen
    sender_list, sender):
  File "/apollo/modules/tools/gen_vehicle_protocol/extract_dbc_meta.py", line 80, in extract_dbc_meta
    items = shlex.split(line)
  File "/usr/local/miniconda2/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/local/miniconda2/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/local/miniconda2/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/local/miniconda2/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

**Comment by muleisheng** [comment]
_line_ may be "".  You could print var line and check if it is "".

**Comment by Carlzhangk** [comment]
@muleisheng Thanks for your comment. Could you please be more specific on where to print var line in the script? I look forward to it.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
