### ISSUE TITLE
Cannot run ./scripts/diagnostics.sh

### ISSUE THREAD

**Issue by alexbuyval** [ApolloAuto/apollo#5772]
Hi all,

When I am trying to run ./scripts/diagnostics.sh, I got the following error:
```
Traceback (most recent call last):
  File "modules/tools/diagnostics/diagnostics.py", line 28, in <module>
    import rospy
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/client.py", line 60, in <module>
    import rospy.impl.init
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/impl/init.py", line 54, in <module>
    from .tcpros import init_tcpros
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/impl/tcpros.py", line 45, in <module>
    import rospy.impl.tcpros_service
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 53, in <module>
    from rospy.impl.tcpros_base import TCPROSTransport, TCPROSTransportProtocol, \
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 61, in <module>
    from rospy.msg import deserialize_messages, serialize_message
  File "/home/tmp/ros/lib/python2.7/dist-packages/rospy/msg.py", line 48, in <module>
    import google.protobuf.message
ImportError: No module named google.protobuf.message
```
However, protobuf already installed into '/usr/local/lib/python2.7/dist-packages/' folder.
I tried to uninstall and install protobuf again. However, I got the same error.

Also I tried to install the protobuf into /home/tmp/ros/lib/python2.7/dist-packages/ folder by the following command:
```
sudo pip install --target=/home/tmp/ros/lib/python2.7/dist-packages --ignore-installed protobuf
```
no lucky again :(

Are there ways to solve this issue?

Alex

**Comment by poutyface** [comment]
This script work for me. 
 
In my enviroment apollo dev docker image (dev-x86_64-20180906_2002)
```
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf
>>> google.protobuf.__path__
['/usr/local/lib/python2.7/dist-packages/google/protobuf']
```
