### ISSUE TITLE
Localization Module coredump

### ISSUE THREAD

**Issue by royzhao** [ApolloAuto/apollo#6311]
### System information

- **Linux Ubuntu 16.04**:
- **Apollo installed from (source)**:
- **Apollo version ( 3.0)**:

### Steps to reproduce the issue:
- **start localization**:
```gdb /apollo/bazel-bin/modules/localization/localization --flagfile=/apollo/modules/localization/conf/localization.conf --log_dir=/apollo/data/log```
- **then coredump**
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdb827700 (LWP 28625)]

Program received signal SIGILL, Illegal instruction.
0x00007ffff7b5ea7a in apollo::localization::msf::MutableMapMarix::MutableMapMarix() ()
   from /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/localization/../../_solib_k8/_U@local_Uinteg_S_S_Clocal_Uinteg___Uexternal_Slocal_Uinteg_Slib/liblocalization_msf.so
(gdb) bt
#0  0x00007ffff7b5ea7a in apollo::localization::msf::MutableMapMarix::MutableMapMarix() ()
   from /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/localization/../../_solib_k8/_U@local_Uinteg_S_S_Clocal_Uinteg___Uexternal_Slocal_Uinteg_Slib/liblocalization_msf.so
#1  0x00007ffff7b643b8 in apollo::localization::msf::LidarLocatorImpl::LidarLocatorImpl() ()
   from /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/localization/../../_solib_k8/_U@local_Uinteg_S_S_Clocal_Uinteg___Uexternal_Slocal_Uinteg_Slib/liblocalization_msf.so
#2  0x00007ffff7b719de in apollo::localization::msf::LidarLocator::LidarLocator() ()
   from /root/.cache/bazel/_bazel_root/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/bin/modules/localization/../../_solib_k8/_U@local_Uinteg_S_S_Clocal_Uinteg___Uexternal_Slocal_Uinteg_Slib/liblocalization_msf.so

```
-**my cpu info **
```
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
stepping        : 4
microcode       : 0x428
cpu MHz         : 3000.080
cache size      : 25600 KB
physical id     : 0
siblings        : 8
core id         : 7
cpu cores       : 8
apicid          : 14
initial apicid  : 14
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase smep erms xsaveopt
bugs            :
bogomips        : 6000.16
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual

```

**Comment by zhouyao4321** [comment]
According to the msg "Illegal instruction", I guess a newer cpu is needed. I test the program on an CPU with intel skylake architecture and the program works fine.

**Comment by royzhao** [comment]
Ops, i will change other algorithm

**Comment by natashadsouza** [comment]
Closing this issue as it appears to be resolved. Feel free to reopen this issue if you have additional questions. Thanks!
