### ISSUE TITLE
configurator.sh is no longer functioning

### ISSUE THREAD

**Issue by james-goin** [ApolloAuto/apollo#8759]
I have noticed that in the newer Apollo builds that configurator.sh is no longer launching. 

### System information
- OS Platform and Distribution: (Linux Ubuntu 14.04)
- Apollo installed from: source (most recent master branch)
- Apollo version: master
- We have tested on multiple systems which were all previously working. 
### Steps to reproduce the issue:
- bash configurator.sh while in docker 

### Supporting materials (screenshots, command lines, code/script snippets):

apollo@in_dev_docker:/apollo$ configurator.sh                  
Traceback (most recent call last):
  File "modules/tools/configurator/configurator.py", line 160, in <module>
    curses.wrapper(main)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "modules/tools/configurator/configurator.py", line 149, in main
    conf = Configurator(stdscr)
  File "modules/tools/configurator/configurator.py", line 61, in __init__
    moduleconf.parse_from_file()
  File "/apollo/modules/tools/configurator/ModuleConf.py", line 47, in parse_from_file
    self.proto = ast.literal_eval("mod." + self.proto_class)
  File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python2.7/ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

Thanks!

**Comment by mickeyouyou** [comment]
fixed and merged into master. thank you .
