### ISSUE TITLE
Build on local machine error

### ISSUE THREAD

**Issue by jinfagang** [ApolloAuto/apollo#9448]
Hi, I want build a standalone cyber lib on my local machine, I got error when run:
```
bazel build cyber:cyber
```

Error:

```
(18:00:20) ERROR: Failed to connect to 'http://cache.host:3588': cannot find a NameResolver for http://cache.host:3588
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
	at com.google.devtools.build.lib.events.Event.<init>(Event.java:52)
	at com.google.devtools.build.lib.events.Event.error(Event.java:162)
	at com.google.devtools.build.lib.events.Event.error(Event.java:197)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:223)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:344)
	at com.google.devtools.build.lib.events.Event.<init>(Event.java:52)
	at com.google.devtools.build.lib.events.Event.error(Event.java:162)
	at com.google.devtools.build.lib.events.Event.error(Event.java:197)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.execExclusively(BlazeCommandDispatcher.java:472)
	at com.google.devtools.build.lib.runtime.BlazeCommandDispatcher.exec(BlazeCommandDispatcher.java:223)
	at com.google.devtools.build.lib.runtime.CommandExecutor.exec(CommandExecutor.java:58)
	at com.google.devtools.build.lib.server.GrpcServerImpl.executeCommand(GrpcServerImpl.java:850)
	at com.google.devtools.build.lib.server.GrpcServerImpl.access$2100(GrpcServerImpl.java:109)
	at com.google.devtools.build.lib.server.GrpcServerImpl$2.lambda$run$0(GrpcServerImpl.java:915)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

What's the problem? Or does there any way to build cyber only on local machine?

**Comment by fengqikai1414** [comment]
@jinfagang This should be a problem with bazel on your local machine.
