### ISSUE TITLE
Apollo 5.0 build interrupted.

### ISSUE THREAD

**Issue by leoncesc** [ApolloAuto/apollo#9952]
After execute the build command: bash apollo.sh build, build interrupted.
My env is: ubuntu 16.04, NVIDIA GPU, Driver Version: 430.50, CUDA Version: 10.1

System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under CPU mode. No GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.
Extracting Bazel installation...
.........
____Loading package: modules/perception/fusion/lib/dummy
____Loading package: modules/planning/common/speed
____Loading package: modules/drivers/video/proto
____Loading package: modules/perception/camera/lib/interface
____Loading package: modules/map/tools/map_datachecker/server
____Loading package: modules/planning/tasks/deciders/path_bounds_decider
____Loading package: modules/planning/tasks/deciders/open_space_decider
____Loading package: modules/planning/tasks/optimizers/open_space_trajectory_generation
____Loading package: modules/drivers/radar/ultrasonic_radar/proto
____Loading package: modules/perception/lidar/lib/segmentation/cnnseg/spp_engine
____Loading package: modules/perception/base
____Loading package: modules/perception/lib/config_manager
____Loading package: modules/perception/radar/lib/roi_filter/hdmap_radar_roi_filter
____Loading package: cyber/logger
____Loading package: cyber/parameter
[INFO] Building on x86_64...
[INFO] Building with --jobs=16 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.
ERROR: (10-18 09:36:00.768) build interrupted.
INFO: (10-18 09:36:00.770) Elapsed time: 140.637s
============================
[ERROR] Build failed!
[INFO] Took 157 seconds
============================

**Comment by natashadsouza** [comment]
@leoncesc which version of Apollo are you trying to build?

**Comment by natashadsouza** [comment]
@leoncesc could you share the steps you used to build Apollo? I would also recommend rebuilding a clean build and sending us a screenshot of the error message you see. Thanks!

**Comment by leoncesc** [comment]
@natashadsouza First, I install docker from .deb file and check it ok. Second, start the container with command bash `docker/scripts/dev_start.sh`, and get into the container `bash docker/scripts/dev_into.sh`. At last, when I build the modules with commnad `bash apollo.sh build`, it reportes an erro "build interrupted" without any tips. The information reported in the terminal is:


root@in_dev_docker:/apollo# bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under CPU mode. No GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.
____Loading package: modules/transform
____Loading package: modules/perception/camera/app
____Loading package: modules/perception/lidar/lib/ground_detector/ground_service_detector
____Loading package: modules/perception/inference
____Loading package: modules/drivers/radar/racobit_radar/proto
____Loading package: modules/common/math/qp_solver
____Loading package: modules/routing/tools
____Loading package: modules/dreamview/backend/sim_control
____Loading package: modules/perception/lidar/lib/scene_manager/ground_service/proto
____Loading package: cyber/node
____Loading package: cyber/examples
____Loading package: cyber/croutine
[INFO] Building on x86_64...
[INFO] Building with --jobs=16 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.
ERROR: (10-21 01:29:17.311) build interrupted.
INFO: (10-21 01:29:17.313) Elapsed time: 134.951s
============================
[ERROR] Build failed!
[INFO] Took 136 seconds
============================

**Comment by fanfanfanf** [comment]
I have the same problem, and I got an info: "INFO: (10-21 01:54:50.672) Timeout connecting to https://github.com/ApolloAuto/apollo-contrib/releases/download/v3.0.0/plat-sw-3.0.0.1.zip", it kept for 1 minute and disappeared when it finally built failed.

**Comment by leoncesc** [comment]
After I add proxy setups in bashrc file in docker, the following problem is reported.

root@in_dev_docker:/apollo# bash apollo.sh build
System check passed. Build continue ...
[WARNING] ESD CAN library supplied by ESD Electronics does not exist. If you need ESD CAN, please refer to third_party/can_card_library/esd_can/README.md.
Running build under CPU mode. No GPU is required to run the build.
[INFO] Start building, please wait ...
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring http_proxy in environment.
WARNING: ignoring LD_PRELOAD in environment.
____Loading package: modules/perception/common/geometry
____Loading package: modules/canbus/vehicle/lincoln
____Loading package: modules/common
____Loading package: cyber/data
____Loading package: cyber/record
____Loading package: cyber/examples/timer_component_example
[INFO] Building on x86_64...
[INFO] Building with --jobs=16 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring http_proxy in environment.
WARNING: ignoring LD_PRELOAD in environment.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@ad_rss_lib' (requested by nodes 'REPOSITORY:@ad_rss_lib')
INFO: (10-21 03:37:14.629) Elapsed time: 6.250s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@ad_rss_lib' (requested by nodes 'REPOSITORY:@ad_rss_lib')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:476)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1488)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3018)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98)
	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:174)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:469)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:296)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at com.google.devtools.build.lib.bazel.repository.GitCloner.clone(GitCloner.java:193)
	at com.google.devtools.build.lib.bazel.repository.NewGitRepositoryFunction.fetch(NewGitRepositoryFunction.java:44)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:401)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.sun.security.ntlm.Client.type3(Client.java:161)
	at sun.net.www.protocol.http.ntlm.NTLMAuthentication.buildType3Msg(NTLMAuthentication.java:250)
	at sun.net.www.protocol.http.ntlm.NTLMAuthentication.setHeaders(NTLMAuthentication.java:225)
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2096)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 19 more
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@ad_rss_lib' (requested by nodes 'REPOSITORY:@ad_rss_lib')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:476)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1488)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3018)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98)
	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:174)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:469)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:296)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at com.google.devtools.build.lib.bazel.repository.GitCloner.clone(GitCloner.java:193)
	at com.google.devtools.build.lib.bazel.repository.NewGitRepositoryFunction.fetch(NewGitRepositoryFunction.java:44)
	at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:188)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:401)
	... 4 more
Caused by: java.lang.NullPointerException
	at com.sun.security.ntlm.Client.type3(Client.java:161)
	at sun.net.www.protocol.http.ntlm.NTLMAuthentication.buildType3Msg(NTLMAuthentication.java:250)
	at sun.net.www.protocol.http.ntlm.NTLMAuthentication.setHeaders(NTLMAuthentication.java:225)
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2096)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 19 more
============================
[ERROR] Build failed!
[INFO] Took 8 seconds
============================

**Comment by alexbuyval** [comment]
@leoncesc How many RAM do you have? Have you got a swap?

Sometimes the build is failed because there is no RAM enough.

**Comment by wutianze** [comment]
Same problem, I tried to build apollo in docker container, and it reports build interrupt without clear error information. My platform is ubuntu 18.04, nvidia GPU, docker 19.03.5.

**Comment by wutianze** [comment]
I find the pre-build process highly depends on the network quaility. Since the downloading from apollo/contrib or others in github sometimes fails, it may cause the problem.

**Comment by davidhopper2003** [comment]
> I find the pre-build process highly depends on the network quaility. Since the downloading from apollo/contrib or others in github sometimes fails, it may cause the problem.

I agree with you.

**Comment by daohu527** [comment]
Closed due to inactivity. If the problem persists, pls feel free to reopen it or create a new one and refer to it.
